// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using taskWebapi.Data;

namespace taskWebapi.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20220125120030_addid")]
    partial class addid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("taskWebapi.Models.Department", b =>
                {
                    b.Property<int>("depId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("depId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("taskWebapi.Models.Designation", b =>
                {
                    b.Property<int>("dsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dsgname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dsgId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("taskWebapi.Models.Employee", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("dsgId")
                        .HasColumnType("int");

                    b.Property<string>("eadd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("esal")
                        .HasColumnType("int");

                    b.HasKey("empId");

                    b.HasIndex("dsgId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("taskWebapi.Models.EmployeeDepartment", b =>
                {
                    b.Property<int>("empId")
                        .HasColumnType("int");

                    b.Property<int>("depId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("empId", "depId");

                    b.HasIndex("depId");

                    b.ToTable("EmployeeDepartments");
                });

            modelBuilder.Entity("taskWebapi.Models.Employee", b =>
                {
                    b.HasOne("taskWebapi.Models.Designation", "tbdsg")
                        .WithMany()
                        .HasForeignKey("dsgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbdsg");
                });

            modelBuilder.Entity("taskWebapi.Models.EmployeeDepartment", b =>
                {
                    b.HasOne("taskWebapi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("depId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taskWebapi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("empId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
